from surrender.io.obj_descriptor import OBJDescriptor


class OBJWriter:
    def __init__(self, shapes):
        self.shapes = shapes

    def generate(self):
        string = "# File generated by SurRender \n\n"

        index = 1
        for i, shape in enumerate(self.shapes):
            descriptor = OBJDescriptor(shape)

            string += f"g Object{i} \n"
            string += descriptor.generate(index) + "\n"

            num_points = len(descriptor.shape().points())
            index += num_points

        return string

    def write(self, path):
        with open(path, "w") as file:
            string = self.generate()
            file.write(string)
